#cloud-config
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y && apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker && systemctl enable docker
  - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - git clone  --branch main https://github.com/carlosmeds/system-observability /home/ubuntu/system-observability
  - chown -R ubuntu:ubuntu /home/ubuntu/system-observability
  - echo "AWS_ACCESS_KEY_ID=${aws_access_key}" >> /home/ubuntu/system-observability/observability/.env
  - echo "AWS_SECRET_ACCESS_KEY=${aws_secret_key}" >> /home/ubuntu/system-observability/observability/.env
  - echo "BUCKET_NAME=${bucket_name}" >> /home/ubuntu/system-observability/observability/.env
  - chown ubuntu:ubuntu /home/ubuntu/system-observability/observability/.env
  - |
    cat <<EOF > /home/ubuntu/system-observability/observability/thanos/s3.yml
    type: S3
    config:
      bucket: "${bucket_name}"
      endpoint: "s3.amazonaws.com"
      region: "us-east-1"
      access_key: "${aws_access_key}"
      secret_key: "${aws_secret_key}"
      insecure: false
    EOF
  - chown ubuntu:ubuntu /home/ubuntu/system-observability/observability/thanos/s3.yml
  - sudo /usr/local/bin/docker-compose -f /home/ubuntu/system-observability/observability/compose.yml up -d